development:
  vkontakte:
    token:  <%= ENV['vkontakte_token'] %>
    key:    <%= ENV['vkontakte_key'] %>
  twitter:
    token:  <%= ENV['twitter_token'] %>
    key:    <%= ENV['twitter_key'] %>

production:
  vkontakte:
    token:  <%= ENV['vkontakte_token'] %>
    key:    <%= ENV['vkontakte_key'] %>
  twitter:
    token:  <%= ENV['twitter_token'] %>
    key:    <%= ENV['twitter_key'] %>

test:
  vkontakte:
    token:  <%= ENV['vkontakte_token'] %>
    key:    <%= ENV['vkontakte_key'] %>
  twitter:
    token:  <%= ENV['twitter_token'] %>
    key:    <%= ENV['twitter_key'] %>
